apiVersion: v1
kind: Service
metadata:
  name: spark-worker 
  labels:
    app: spark-worker
spec:
  clusterIP: None
  ports:
  - name: worker
    port: 8077
  - name: webui
    port: 8081
  - name: driver
    port: 9077
  - name: blockmanager
    port: 9087
  selector:
    app: spark-worker
