apiVersion: v1
kind: Service
metadata:
  name: spark-master 
  labels:
    app: spark-master
spec:
  clusterIP: None
  ports:
  - name: applicationui
    port: 4040
  - name: master
    port: 7077
  - name: webui
    port: 8080
  selector:
    app: spark-master
