version: "3.5"
services:

  spark-base:
    container_name: spark-base
    build: ./spark-base
    image: spark-base:latest

  spark-master:
    depends_on:
      - spark-base
    container_name: spark-master
    image: spark-base:latest
    ports:
      - "4040:4040"
      - "8080:8080"
    command: ["/opt/spark/sbin/start-master.sh"]
    networks:
      - spark-cluster 
    volumes:
      - ./events:/tmp/spark-events

  spark-worker:
    depends_on:
      - spark-master
    image: spark-base:latest
    expose:
      - "8081"
    ports: 
      - "0:8081"
    command: ["/opt/spark/sbin/start-slave.sh", "spark://spark-master:7077"]
    networks:
      - spark-cluster
    volumes:
      - ./events:/tmp/spark-events

  spark-history:
    depends_on:
      - spark-master
    container_name: spark-history
    image: spark-base:latest
    ports:
      - "18080:18080"
    command: ["/opt/spark/sbin/start-history-server.sh"]
    networks:
      - spark-cluster
    volumes:
      - ./events:/tmp/spark-events

  spark-notebook:
    depends_on:
      - spark-master
    container_name: spark-notebook
    image: jupyter/all-spark-notebook
    ports:
      - "8888:8888"
    networks:
      - spark-cluster
    volumes:
      - ./work:/home/jovyan/work
      - ./events:/tmp/spark-events
    command: ["start-notebook.sh", "--NotebookApp.password='sha1:9fd15fe4a4ce:0b0a713b2cc29caabb2228971971bae993cb86d2'"]

networks:
  spark-cluster:
    name: spark-cluster
