apiVersion: v1
kind: Service
metadata:
  name: spark-notebook 
  labels:
    app: spark-notebook
spec:
  type: LoadBalancer
  ports:
  - name: notebook
    port: 8888
    targetPort: 8888
  - name: webui
    port: 4040
    targetPort: 4040
  - name: driver
    port: 7079
    targetPort: 7079
  selector:
    app: spark-notebook
