apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spark-notebook
spec:
  selector:
    matchLabels:
      app: spark-notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-notebook
    spec:
      containers:
      - name: spark-notebook
        image: jupyter/all-spark-notebook # or just image: redis
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.password='sha1:9fd15fe4a4ce:0b0a713b2cc29caabb2228971971bae993cb86d2'"]
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 8888
